version = 0.1
[default.deploy.parameters]
stack_name = "stocks-microservice"
resolve_s3 = true
s3_prefix = "stocks-microservice"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaAuthorizerArn=\"arn:aws:lambda:us-east-1:891377404175:function:authorizer-lambda-function-production\" TagEnvironment=\"production\" TagProject=\"studying-serverless\""
image_repositories = []
